import React from 'react';
import { Product, Theme, Translations, Notification } from './types';

interface ThemeStyles {
  light: React.CSSProperties & { [key: string]: any };
  dark: React.CSSProperties & { [key: string]: any };
  'high-contrast': React.CSSProperties & { [key: string]: any };
}

interface AppTheme {
  products: Product[];
  styles: ThemeStyles;
}

const electronicsProducts: Product[] = [
  {
    id: 1,
    name: 'Quantum Laptop',
    description: 'A high-performance laptop with a sleek design, perfect for professionals and creatives. Features a 16-inch Retina display.',
    price: 1499.99,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop',
    category: 'Laptops',
    tags: ['New'],
    stock: { level: 'in-stock', quantity: 25 },
    colors: ['#808080', '#e0e0e0'],
    videoUrl: 'https://videos.pexels.com/video-files/3214532/3214532-hd_1920_1080_25fps.mp4',
    specifications: {
      'Processor': 'Quantum Core i9',
      'Memory': '32GB DDR5 RAM',
      'Storage': '1TB NVMe SSD',
      'Display': '16-inch Liquid Retina XDR',
      'Graphics': 'Quantum GPU 16-Core',
    },
    reviews: [
      { id: 1, author: 'Alex D.', rating: 5, comment: 'This laptop is an absolute powerhouse. Renders videos in no time!' },
      { id: 2, author: 'Jenna M.', rating: 4, comment: 'Great for design work, but the battery life could be a bit better under heavy load.' },
    ],
    story: {
        title: "Unleash Your Ambition",
        narrative: "From the first spark of an idea to the final render, the Quantum Laptop is your silent partner. Engineered for the ambitious, its power flows as fast as your thoughts, turning complex code into seamless reality and wild dreams into stunning visuals. This isn't just a machine; it's the canvas for your next masterpiece.",
        imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726a?q=80&w=1200&auto=format&fit=crop",
        videoUrl: 'https://videos.pexels.com/video-files/5901323/5901323-hd_1920_1080_30fps.mp4'
    },
    priceHistory: [
      { date: '2023-01-01', price: 1599.99 },
      { date: '2023-03-15', price: 1549.99 },
      { date: '2023-06-01', price: 1499.99 },
      { date: '2023-09-01', price: 1499.99 },
    ]
  },
  {
    id: 2,
    name: 'Nova Smartphone',
    description: 'The latest in mobile technology, with a stunning OLED screen and a powerful triple-camera system.',
    price: 999.0,
    imageUrl: 'https://images.unsplash.com/photo-1587560699343-6d15b28536a6?q=80&w=800&auto=format&fit=crop',
    category: 'Smartphones',
    stock: { level: 'low', quantity: 8 },
    colors: ['#1e1e1e', '#f5f5f7', '#ffc107'],
    specifications: {
        'Display': '6.7-inch Super Retina XDR OLED',
        'Camera': 'Triple 12MP system (Ultra Wide, Wide, Telephoto)',
        'Processor': 'A16 Bionic Chip',
        'Battery': 'Up to 28 hours video playback',
        'Storage': '256GB',
    },
    reviews: [
        { id: 1, author: 'Mike P.', rating: 5, comment: 'The camera is incredible, especially in low light. The screen is gorgeous.' },
        { id: 2, author: 'Sara K.', rating: 4, comment: 'Super fast and responsive. A worthy upgrade.' },
    ],
  },
  {
    id: 3,
    name: 'Aura Headphones',
    description: 'Immersive noise-cancelling headphones that deliver crystal-clear audio. 30-hour battery life.',
    price: 349.50,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    category: 'Audio',
    tags: ['Best Seller'],
    stock: { level: 'in-stock', quantity: 50 },
    colors: ['#000000', '#ffffff', '#007bff'],
    specifications: {
        'Type': 'Over-ear, closed-back',
        'Connectivity': 'Bluetooth 5.2, 3.5mm audio jack',
        'Battery Life': 'Up to 30 hours with ANC',
        'Features': 'Active Noise Cancellation, Transparency Mode, Spatial Audio',
        'Weight': '254g',
    },
    reviews: [
        { id: 1, author: 'David L.', rating: 5, comment: 'The noise cancellation is magic. I can finally focus in my open office.' },
        { id: 2, author: 'Chloe R.', rating: 5, comment: 'Sound quality is top-notch. They are also super comfortable for long listening sessions.' },
    ],
    story: {
        title: "Find Your Focus",
        narrative: "Silence the world and dive into pure sound. The Aura Headphones create a sanctuary for your senses, where every note is crisp and every beat is profound. Whether you're finding your rhythm in a bustling city or seeking tranquility, Aura is your escape to an immersive world of audio.",
        imageUrl: "https://images.unsplash.com/photo-1511303853424-73d756c12808?q=80&w=1200&auto=format&fit=crop",
        videoUrl: "https://videos.pexels.com/video-files/3130323/3130323-hd_1920_1080_30fps.mp4"
    }
  },
  {
    id: 4,
    name: 'Ergo-Mouse Pro',
    description: 'Ergonomically designed for comfort and precision. Features customizable buttons and adjustable DPI.',
    price: 89.99,
    imageUrl: 'https://images.unsplash.com/photo-1629429408209-1f9122651d37?q=80&w=800&auto=format&fit=crop',
    category: 'Peripherals',
    stock: { level: 'out-of-stock', quantity: 0 },
    specifications: {
        'Sensor': 'Optical',
        'DPI': '200 - 16,000',
        'Buttons': '8 programmable buttons',
        'Connectivity': '2.4GHz Wireless, Bluetooth',
        'Ergonomics': 'Right-handed vertical design',
    },
    reviews: [
        { id: 1, author: 'GamerX', rating: 5, comment: 'Perfect for long gaming sessions. Super precise and the customizable buttons are a game-changer.' },
        { id: 2, author: 'OfficeWorker', rating: 5, comment: 'My wrist pain is gone! Took a day to get used to, but now I can\'t go back.' },
    ],
  },
  {
    id: 5,
    name: 'StreamCam HD',
    description: 'Full 1080p HD webcam with smart auto-focus and exposure for professional-quality streaming.',
    price: 169.0,
    imageUrl: 'https://images.unsplash.com/photo-1593106578502-28fa75da9d99?q=80&w=800&auto=format&fit=crop',
    category: 'Peripherals',
    stock: { level: 'in-stock', quantity: 30 },
    specifications: {
        'Resolution': '1080p / 60fps',
        'Focus Type': 'Autofocus',
        'Field of View': '78 degrees',
        'Microphone': 'Dual omni-directional',
        'Connectivity': 'USB-C',
    },
    reviews: [
        { id: 1, author: 'StreamQueen', rating: 5, comment: 'The video quality is amazing, my stream has never looked better.' },
        { id: 2, author: 'RemoteWorker', rating: 5, comment: 'Makes me look so much more professional in Zoom meetings. The auto-exposure is fantastic.' },
    ],
  },
  {
    id: 6,
    name: 'Mech-Keyboard X',
    description: 'A mechanical keyboard with customizable RGB backlighting and satisfying tactile feedback.',
    price: 199.99,
    imageUrl: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=800&auto=format&fit=crop',
    category: 'Peripherals',
    stock: { level: 'in-stock', quantity: 15 },
    specifications: {
        'Switch Type': 'Tactile Brown Switches',
        'Layout': 'Tenkeyless (87 keys)',
        'Backlighting': 'Per-key RGB',
        'Connectivity': 'Wired (USB-C)',
        'Frame': 'Anodized Aluminum',
    },
    reviews: [
        { id: 1, author: 'CodeWizard', rating: 5, comment: 'The typing experience is a dream. Solid build quality and the RGB is a nice touch.' },
        { id: 2, author: 'ProGamer', rating: 4, comment: 'Great keyboard for gaming, very responsive. Wish it had a wireless option.' },
    ],
  },
  {
    id: 7,
    name: 'Smart Watch G2',
    description: 'Track your fitness, notifications, and more with this stylish and feature-packed smartwatch.',
    price: 249.0,
    imageUrl: 'https://images.unsplash.com/photo-1544117519-31a4b719223d?q=80&w=800&auto=format&fit=crop',
    category: 'Wearables',
    stock: { level: 'low', quantity: 10 },
    colors: ['#333333', '#c0c0c0', '#f0e68c'],
    specifications: {
        'Display': '1.4-inch AMOLED',
        'Compatibility': 'iOS and Android',
        'Sensors': 'Heart Rate, SpO2, GPS',
        'Battery Life': 'Up to 14 days',
        'Water Resistance': '5 ATM',
    },
    reviews: [
        { id: 1, author: 'FitFreak', rating: 5, comment: 'Love this watch for tracking my runs. The GPS is accurate and the battery lasts forever.' },
        { id: 2, author: 'BusyBee', rating: 4, comment: 'Looks great and the notifications are super helpful. The app ecosystem could be a bit larger.' },
    ],
  },
  {
    id: 8,
    name: 'Titan Gaming PC',
    description: 'A powerhouse gaming desktop with the latest GPU and CPU for an unparalleled gaming experience.',
    price: 2999.0,
    imageUrl: 'https://images.unsplash.com/photo-1598986646512-9213b0ae9387?q=80&w=800&auto=format&fit=crop',
    category: 'Gaming',
    tags: ['Best Seller'],
    stock: { level: 'in-stock', quantity: 5 },
    specifications: {
        'CPU': 'Intel Core i9-13900K',
        'GPU': 'NVIDIA GeForce RTX 4090',
        'RAM': '64GB DDR5 6000MHz',
        'Storage': '4TB NVMe SSD',
        'Case': 'Custom liquid-cooled chassis',
    },
    reviews: [
        { id: 1, author: 'MaxSettings', rating: 5, comment: 'This thing is an absolute beast. Runs every game I throw at it on max settings without breaking a sweat.' },
        { id: 2, author: 'VR_Enthusiast', rating: 5, comment: 'Incredible performance for VR. Super smooth and immersive. Worth every penny.' },
    ],
    story: {
        title: "Enter a New Reality",
        narrative: "Beyond the screen lies a universe of infinite possibilities. The Titan Gaming PC is your vessel, a marvel of engineering built to shatter boundaries and redefine immersion. Experience games not as a player, but as a hero living in a world of breathtaking detail and lightning-fast response.",
        imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop"
    }
  },
];

const youthfulProducts: Product[] = [
    { 
        id: 9, 
        name: 'Vibe Sneakers', 
        description: 'Ultra-comfortable sneakers with a retro-futuristic design.', 
        price: 129.99, 
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ab?q=80&w=800&auto=format&fit=crop',
        category: 'Footwear',
        tags: ['Best Seller'],
        stock: { level: 'in-stock', quantity: 100 },
        colors: ['#ffffff', '#000000', '#ff00ff'],
        specifications: {
            'Upper Material': 'Knit Mesh and Synthetic Overlays',
            'Sole': 'Chunky Rubber Outsole',
            'Closure': 'Lace-up',
            'Style': '90s Retro-Futurism',
        },
        reviews: [
            { id: 1, author: 'StyleIcon', rating: 5, comment: 'So comfy and they look amazing. I get compliments everywhere I go!' },
            { id: 2, author: 'EverydayJoe', rating: 5, comment: 'My new favorite daily shoes. Great for walking around the city.' },
        ],
        story: {
            title: "Walk Your Own Path",
            narrative: "The city is your playground, every street a new adventure. The Vibe Sneakers are more than just footwear; they're a statement. Laced with the energy of the streets and designed for those who dare to be different, they carry you from spontaneous late-night hangouts to sun-drenched festival fields. Where will they take you next?",
            imageUrl: "https://images.unsplash.com/photo-1528701800487-ba01743862a9?q=80&w=1200&auto=format&fit=crop"
        }
    },
    { 
        id: 10, 
        name: 'Neon Beats Headphones', 
        description: 'Wireless headphones with vibrant LED accents and deep bass.', 
        price: 199.00, 
        imageUrl: 'https://images.unsplash.com/photo-1545127398-14699f92334b?q=80&w=800&auto=format&fit=crop', 
        category: 'Accessories',
        stock: { level: 'in-stock', quantity: 40 },
        specifications: {
            'Type': 'On-ear',
            'Connectivity': 'Bluetooth 5.0',
            'Features': 'Customizable LED lights, Enhanced Bass Mode',
            'Battery Life': 'Up to 25 hours',
        },
        reviews: [
            { id: 1, author: 'DJ_Vibes', rating: 5, comment: 'The bass is insane and the lights sync up with my music. Perfect for parties.' },
            { id: 2, author: 'Tina', rating: 4, comment: 'They sound great and are really fun, but a bit flashy for the office.' },
        ],
    },
    { 
        id: 11, 
        name: 'Pixel Art Display', 
        description: 'A programmable LED display for your desk to show off your pixel art.', 
        price: 249.50, 
        imageUrl: 'https://images.unsplash.com/photo-1604502528143-7a6c533446b3?q=80&w=800&auto=format&fit=crop', 
        category: 'Gear',
        tags: ['New'],
        stock: { level: 'low', quantity: 9 },
        specifications: {
            'Resolution': '64x64 Pixels',
            'Display Size': '10 inches',
            'Connectivity': 'Wi-Fi, Bluetooth',
            'Features': 'Mobile App for creation, Social Notifications',
        },
        reviews: [
            { id: 1, author: 'PixelPete', rating: 5, comment: 'I love this thing! So much fun to create animations and show them off on my stream.' },
            { id: 2, author: 'GeekChic', rating: 5, comment: 'A perfect piece of decor for my geeky office. The app is easy to use.' },
        ],
    },
    { 
        id: 12, 
        name: 'Kickflip Pro Skateboard', 
        description: 'A durable and stylish skateboard for all skill levels.', 
        price: 89.99, 
        imageUrl: 'https://images.unsplash.com/photo-1547466838-8d43d3a53c8c?q=80&w=800&auto=format&fit=crop',
        category: 'Gear',
        stock: { level: 'in-stock', quantity: 60 },
        specifications: {
            'Deck Material': '7-ply Canadian Maple',
            'Size': '8.25" x 32"',
            'Trucks': 'Lightweight Aluminum',
            'Wheels': '54mm 99A Urethane',
        },
        reviews: [
            { id: 1, author: 'Skaterboi', rating: 5, comment: 'Great pop and super durable deck. The bearings are smooth right out of the box.' },
            { id: 2, author: 'Newbie', rating: 4, comment: 'Awesome first board! The graphic is sick.' },
        ],
        story: {
            title: "Define Your Ride",
            narrative: "Feel the grip, hear the roll, and own the pavement. The Kickflip Pro isn't just a board; it's an extension of you. Built for the park, the street, and everywhere in between, it’s your trusted companion for landing that trick you've been practicing for weeks. It’s freedom on four wheels.",
            imageUrl: "https://images.unsplash.com/photo-1559497843-55c3c06a374a?q=80&w=1200&auto=format&fit=crop",
            videoUrl: "https://videos.pexels.com/video-files/5192224/5192224-hd_1920_1080_25fps.mp4"
        }
    },
    { 
        id: 13, 
        name: 'Creator Ring Light', 
        description: 'Get perfect lighting for your streams and videos with this versatile ring light.', 
        price: 79.00, 
        imageUrl: 'https://images.unsplash.com/photo-1604335293424-73d756c12808?q=80&w=800&auto=format&fit=crop', 
        category: 'Gear',
        stock: { level: 'in-stock', quantity: 20 },
        specifications: {
            'Size': '18-inch Diameter',
            'Color Temperature': '3200K - 5600K Adjustable',
            'Brightness Levels': '10',
            'Power Source': 'AC Adapter',
        },
        reviews: [
            { id: 1, author: 'InstaFamous', rating: 5, comment: 'A must-have for any content creator. My photos and videos look so much better.' },
            { id: 2, author: 'TikTokStar', rating: 5, comment: 'The adjustable color and brightness are perfect. Easy to set up.' },
        ],
    },
    { 
        id: 14, 
        name: 'Graffiti Art Hoodie', 
        description: 'A comfortable oversized hoodie featuring unique street art designs.', 
        price: 69.99, 
        imageUrl: 'https://images.unsplash.com/photo-1556819842-15a3a0e1a1b3?q=80&w=800&auto=format&fit=crop', 
        category: 'Apparel',
        stock: { level: 'out-of-stock', quantity: 0 },
        specifications: {
            'Material': '80% Cotton, 20% Polyester Fleece',
            'Fit': 'Oversized, Drop Shoulder',
            'Care': 'Machine wash cold, tumble dry low',
            'Features': 'Kangaroo Pocket, Printed Sleeves',
        },
        reviews: [
            { id: 1, author: 'UrbanExplorer', rating: 5, comment: 'Super comfy and the design is fire. I live in this hoodie now.' },
            { id: 2, author: 'Jess', rating: 5, comment: 'Great quality material, feels really soft.' },
        ],
    },
    { 
        id: 15, 
        name: 'RGB Gaming Mouse', 
        description: 'A high-precision gaming mouse with customizable RGB lighting.', 
        price: 59.00, 
        imageUrl: 'https://images.unsplash.com/photo-1600981335960-a2420938a16c?q=80&w=800&auto=format&fit=crop', 
        category: 'Accessories',
        stock: { level: 'in-stock', quantity: 80 },
        specifications: {
            'DPI': 'Up to 12,000',
            'Sensor': 'PixArt Optical Sensor',
            'Buttons': '6 programmable',
            'Lighting': '16.8 million color RGB',
        },
        reviews: [
            { id: 1, author: 'FPS_King', rating: 5, comment: 'Lightweight and super accurate. The RGB effects are really cool too.' },
            { id: 2, author: 'CasualGamer', rating: 4, comment: 'Awesome mouse for the price. The software is easy to use.' },
        ],
    },
    { 
        id: 16, 
        name: 'Synthwave Desk Mat', 
        description: 'A large desk mat with a cool, retro synthwave design.', 
        price: 39.00, 
        imageUrl: 'https://images.unsplash.com/photo-1557682250-33bd709cbe85?q=80&w=800&auto=format&fit=crop', 
        category: 'Accessories',
        stock: { level: 'in-stock', quantity: 120 },
        specifications: {
            'Dimensions': '900mm x 400mm x 4mm',
            'Material': 'Micro-woven Cloth Surface',
            'Surface': 'Optimized for all mouse sensors',
            'Edge': 'Stitched Edges',
        },
        reviews: [
            { id: 1, author: 'RetroWaveFan', rating: 5, comment: 'The perfect vibe for my setup. It\'s huge and my mouse glides on it.' },
            { id: 2, author: 'WFH_Pro', rating: 5, comment: 'Adds a nice pop of color to my home office and protects my desk.' },
        ],
    },
];

const fashionProducts: Product[] = [
    { 
        id: 17, 
        name: 'Chrono-Elegance Watch', 
        description: 'A timeless timepiece combining classic design with modern mechanics.', 
        price: 1250.00, 
        imageUrl: 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?q=80&w=800&auto=format&fit=crop',
        category: 'Accessories',
        tags: ['Best Seller'],
        stock: { level: 'in-stock', quantity: 12 },
        specifications: {
            'Case Material': '316L Stainless Steel',
            'Movement': 'Swiss Automatic (ETA 2824-2)',
            'Crystal': 'Sapphire Crystal',
            'Water Resistance': '100 meters / 10 ATM',
            'Strap': 'Genuine Alligator Leather',
        },
        reviews: [
            { id: 1, author: 'Connoisseur', rating: 5, comment: 'Exquisite craftsmanship. The sweeping second hand is mesmerizing. A true heirloom piece.' },
            { id: 2, author: 'CEO', rating: 5, comment: 'The perfect dress watch. Understated, elegant, and radiates quality.' },
        ],
        story: {
            title: "A Legacy on Your Wrist",
            narrative: "Time is the ultimate luxury. The Chrono-Elegance isn't just about telling time; it's about owning it. Each tick is a reminder of moments lived and memories made. Forged with precision and designed with soul, it's a testament to timeless style that transcends fleeting trends. It's not just a watch; it's your story.",
            imageUrl: "https://images.unsplash.com/photo-1620625515032-6ed2a1438834?q=80&w=1200&auto=format&fit=crop"
        }
    },
    { 
        id: 18, 
        name: 'The Voyager Leather Bag', 
        description: 'A handcrafted leather satchel perfect for the modern professional.', 
        price: 450.00, 
        imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop', 
        category: 'Bags',
        stock: { level: 'low', quantity: 7 },
        specifications: {
            'Material': 'Full-Grain Italian Leather',
            'Dimensions': '15" x 11" x 4"',
            'Compartments': 'Padded laptop sleeve (fits 15" laptop), 2 interior pockets',
            'Strap': 'Adjustable and detachable shoulder strap',
        },
        reviews: [
            { id: 1, author: 'Lawyer', rating: 5, comment: 'The leather is beautiful and has aged wonderfully. I get so many compliments.' },
            { id: 2, author: 'Consultant', rating: 5, comment: 'Spacious enough for all my essentials, but still looks sleek and professional.' },
        ],
    },
    { 
        id: 19, 
        name: 'Silk Scarf "Monarch"', 
        description: 'An elegant silk scarf with a vibrant, artistic butterfly print.', 
        price: 120.00, 
        imageUrl: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?q=80&w=800&auto=format&fit=crop', 
        category: 'Accessories',
        stock: { level: 'in-stock', quantity: 35 },
        colors: ['#ffc0cb', '#87ceeb', '#90ee90'],
        specifications: {
            'Material': '100% Mulberry Silk',
            'Dimensions': '35" x 35" (90cm x 90cm)',
            'Care': 'Dry clean only',
            'Weave': 'Twill',
        },
        reviews: [
            { id: 1, author: 'ArtLover', rating: 5, comment: 'The colors are even more vibrant in person. A true work of art.' },
            { id: 2, author: 'GiftGiver', rating: 5, comment: 'Bought this as a gift for my wife and she adores it. The quality is exceptional.' },
        ],
    },
    { 
        id: 20, 
        name: 'Trench Coat "London Fog"', 
        description: 'A classic, all-weather trench coat that never goes out of style.', 
        price: 380.00, 
        imageUrl: 'https://images.unsplash.com/photo-1517942491322-1c6ada40a2c0?q=80&w=800&auto=format&fit=crop',
        category: 'Apparel',
        tags: ['New'],
        stock: { level: 'in-stock', quantity: 22 },
        colors: ['#f5f5dc', '#d2b48c', '#000000'],
        videoUrl: "https://videos.pexels.com/video-files/8053350/8053350-hd_1920_1080_25fps.mp4",
        specifications: {
            'Material': '100% Cotton Gabardine',
            'Lining': 'Vintage Check',
            'Closure': 'Double-breasted button closure',
            'Details': 'Epaulettes, hook-and-eye collar closure, gun flap, belted cuffs, D-ring belt',
            'Care': 'Dry clean only',
        },
        reviews: [
            { id: 1, author: 'Eleanor V.', rating: 5, comment: 'An absolute classic. The quality is impeccable and it truly elevates any outfit.' },
            { id: 2, author: 'James B.', rating: 5, comment: 'Perfect for the unpredictable city weather. Stylish and functional.' },
        ],
        story: {
            title: "The Signature of Style",
            narrative: "Through misty mornings and rain-slicked city streets, the London Fog trench coat is your shield of sophistication. Its iconic silhouette whispers tales of timeless elegance and quiet confidence. It's more than a coat—it's an armor of grace for the modern romantic.",
            imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1200&auto=format&fit=crop"
        }
    },
    { 
        id: 21, 
        name: 'Velvet Evening Gown', 
        description: 'A stunning, floor-length velvet gown for special occasions.', 
        price: 600.00, 
        imageUrl: 'https://images.unsplash.com/photo-1595509553306-932f91b6c771?q=80&w=800&auto=format&fit=crop', 
        category: 'Apparel',
        stock: { level: 'low', quantity: 4 },
        colors: ['#800000', '#000080', '#006400'],
        specifications: {
            'Fabric': 'Stretch Velvet',
            'Fit': 'Mermaid Silhouette',
            'Length': 'Floor-length',
            'Care': 'Dry clean only',
        },
        reviews: [
            { id: 1, author: 'GalaGoer', rating: 5, comment: 'Felt like a movie star in this dress. It fits like a glove and the material is so luxurious.' },
            { id: 2, author: 'Bella', rating: 5, comment: 'I wore this to a wedding and received so many compliments. It\'s absolutely timeless.' },
        ],
    },
    { 
        id: 22, 
        name: 'Suede Ankle Boots', 
        description: 'Stylish and comfortable suede boots that complement any outfit.', 
        price: 180.00, 
        imageUrl: 'https://images.unsplash.com/photo-1519758369395-97995f54032b?q=80&w=800&auto=format&fit=crop', 
        category: 'Footwear',
        stock: { level: 'in-stock', quantity: 45 },
        colors: ['#a0522d', '#696969'],
        specifications: {
            'Upper Material': 'Genuine Suede',
            'Heel Height': '2.5 inches (6.5cm)',
            'Sole': 'Rubber',
            'Closure': 'Side Zipper',
        },
        reviews: [
            { id: 1, author: 'Fashionista', rating: 5, comment: 'The perfect everyday boot. They are comfortable enough to walk in all day but still look chic.' },
            { id: 2, author: 'AutumnLover', rating: 5, comment: 'I love the rich color. They go with everything from jeans to dresses.' },
        ],
    },
    { 
        id: 23, 
        name: 'Designer Sunglasses', 
        description: 'Protect your eyes in style with these chic, oversized sunglasses.', 
        price: 250.00, 
        imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800&auto=format&fit=crop', 
        category: 'Accessories',
        stock: { level: 'out-of-stock', quantity: 0 },
        specifications: {
            'Frame Material': 'Acetate',
            'Lens': 'Polarized, Gradient',
            'UV Protection': '100% UVA/UVB',
            'Size': '58-18-145',
        },
        reviews: [
            { id: 1, author: 'Sunny', rating: 5, comment: 'So glamorous! The quality is amazing and they feel very sturdy.' },
            { id: 2, author: 'Traveler', rating: 5, comment: 'Great for cutting down glare. I take them with me everywhere.' },
        ],
    },
    { 
        id: 24, 
        name: 'Cashmere Sweater', 
        description: 'Experience ultimate comfort and luxury with this 100% cashmere sweater.', 
        price: 300.00, 
        imageUrl: 'https://images.unsplash.com/photo-1620799140159-48301732642a?q=80&w=800&auto=format&fit=crop', 
        category: 'Apparel',
        stock: { level: 'in-stock', quantity: 30 },
        colors: ['#f5f5dc', '#dcdcdc', '#add8e6'],
        specifications: {
            'Material': '100% Grade-A Cashmere',
            'Knit': '2-ply',
            'Fit': 'Classic Crewneck',
            'Care': 'Hand wash or dry clean',
        },
        reviews: [
            { id: 1, author: 'LuxuryLover', rating: 5, comment: 'Incredibly soft and warm without being bulky. An investment piece that I\'ll have for years.' },
            { id: 2, author: 'Minimalist', rating: 5, comment: 'The perfect sweater. Simple, elegant, and goes with everything.' },
        ],
    },
];

const sharedLightStyles = {
    '--shimmer-color': 'rgba(0, 0, 0, 0.08)',
    '--badge-text-color': '#111827',
};

const sharedDarkStyles = {
    '--shimmer-color': 'rgba(255, 255, 255, 0.08)',
    '--badge-text-color': '#FFFFFF',
};

const highContrastStyles = {
    ...sharedDarkStyles,
    '--font-family': "'Poppins', sans-serif",
    '--background-primary': '#000000',
    '--background-primary-translucent': 'rgba(0, 0, 0, 0.8)',
    '--background-secondary': '#1a1a1a',
    '--background-tertiary': '#333333',
    '--text-primary': '#ffffff',
    '--text-secondary': '#e6e6e6',
    '--text-tertiary': '#cccccc',
    '--primary-accent': '#ffff00', // Yellow
    '--primary-accent-hover': '#ffdd00',
    '--primary-accent-aurora': 'rgba(255, 255, 0, 0.2)',
    '--border-color': '#666666',
    '--border-radius': '0.25rem',
    '--header-gradient-from': '#ffff00',
    '--header-gradient-to': '#00ffff', // Cyan
    '--bg-gradient-1': '#000000',
    '--bg-gradient-2': '#0a0a0a',
    '--bg-gradient-3': '#000000',
    '--badge-text-color': '#000000', // Black text on bright badges
};


export const themes: Record<Theme, AppTheme> = {
  [Theme.Electronics]: {
    products: electronicsProducts,
    styles: {
      light: {
        ...sharedLightStyles,
        '--font-family': "'Poppins', sans-serif",
        '--background-primary': '#f9fafb',
        '--background-primary-translucent': 'rgba(249, 250, 251, 0.6)',
        '--background-secondary': '#ffffff',
        '--background-tertiary': '#f3f4f6',
        '--text-primary': '#111827',
        '--text-secondary': '#374151',
        '--text-tertiary': '#6b7280',
        '--primary-accent': '#0ea5e9',
        '--primary-accent-hover': '#38bdf8',
        '--primary-accent-aurora': 'rgba(14, 165, 233, 0.15)',
        '--border-color': '#e5e7eb',
        '--border-radius': '0.5rem',
        '--header-gradient-from': '#a78bfa',
        '--header-gradient-to': '#38bdf8',
        '--bg-gradient-1': '#f0f9ff',
        '--bg-gradient-2': '#e0f2fe',
        '--bg-gradient-3': '#f0f9ff',
      },
      dark: {
        ...sharedDarkStyles,
        '--font-family': "'Poppins', sans-serif",
        '--background-primary': '#111827',
        '--background-primary-translucent': 'rgba(17, 24, 39, 0.6)',
        '--background-secondary': '#1f2937',
        '--background-tertiary': '#374151',
        '--text-primary': '#f9fafb',
        '--text-secondary': '#d1d5db',
        '--text-tertiary': '#9ca3af',
        '--primary-accent': '#22d3ee',
        '--primary-accent-hover': '#67e8f9',
        '--primary-accent-aurora': 'rgba(34, 211, 238, 0.15)',
        '--border-color': '#374151',
        '--border-radius': '0.5rem',
        '--header-gradient-from': '#a78bfa',
        '--header-gradient-to': '#67e8f9',
        '--bg-gradient-1': '#0f172a',
        '--bg-gradient-2': '#1e293b',
        '--bg-gradient-3': '#132a4a',
      },
      'high-contrast': highContrastStyles,
    },
  },
  [Theme.Youthful]: {
    products: youthfulProducts,
    styles: {
        light: {
            ...sharedLightStyles,
            '--font-family': "'Poppins', sans-serif",
            '--background-primary': '#ffffff',
            '--background-primary-translucent': 'rgba(255, 255, 255, 0.6)',
            '--background-secondary': '#f9f9f9',
            '--background-tertiary': '#eef2f7',
            '--text-primary': '#1a1a2e',
            '--text-secondary': '#555770',
            '--text-tertiary': '#898a9a',
            '--primary-accent': '#e94560',
            '--primary-accent-hover': '#f36d84',
            '--primary-accent-aurora': 'rgba(233, 69, 96, 0.2)',
            '--border-color': '#eef2f7',
            '--border-radius': '1rem',
            '--header-gradient-from': '#f9a8d4',
            '--header-gradient-to': '#e94560',
            '--bg-gradient-1': '#fff1f2',
            '--bg-gradient-2': '#ffe4e6',
            '--bg-gradient-3': '#fff1f2',
        },
        dark: {
            ...sharedDarkStyles,
            '--font-family': "'Poppins', sans-serif",
            '--background-primary': '#1a1a2e',
            '--background-primary-translucent': 'rgba(26, 26, 46, 0.6)',
            '--background-secondary': '#16213e',
            '--background-tertiary': '#0f3460',
            '--text-primary': '#ffffff',
            '--text-secondary': '#a7a9be',
            '--text-tertiary': '#e94560',
            '--primary-accent': '#e94560',
            '--primary-accent-hover': '#f9a8d4',
            '--primary-accent-aurora': 'rgba(233, 69, 96, 0.2)',
            '--border-color': '#0f3460',
            '--border-radius': '1rem',
            '--header-gradient-from': '#f9a8d4',
            '--header-gradient-to': '#e94560',
            '--bg-gradient-1': '#1a1a2e',
            '--bg-gradient-2': '#16213e',
            '--bg-gradient-3': '#2e1a2a',
        },
        'high-contrast': highContrastStyles,
    },
  },
  [Theme.Fashion]: {
    products: fashionProducts,
    styles: {
      light: {
        ...sharedLightStyles,
        '--font-family': "'Playfair Display', serif",
        '--background-primary': '#f5f5f4',
        '--background-primary-translucent': 'rgba(245, 245, 244, 0.6)',
        '--background-secondary': '#ffffff',
        '--background-tertiary': '#e7e5e4',
        '--text-primary': '#2d2d2d',
        '--text-secondary': '#57534e',
        '--text-tertiary': '#78716c',
        '--primary-accent': '#ca8a04',
        '--primary-accent-hover': '#eab308',
        '--primary-accent-aurora': 'rgba(202, 138, 4, 0.15)',
        '--border-color': '#d6d3d1',
        '--border-radius': '0.25rem',
        '--header-gradient-from': '#fde047',
        '--header-gradient-to': '#ca8a04',
        '--bg-gradient-1': '#fefce8',
        '--bg-gradient-2': '#fef9c3',
        '--bg-gradient-3': '#fefce8',
      },
      dark: {
        ...sharedDarkStyles,
        '--font-family': "'Playfair Display', serif",
        '--background-primary': '#2d2d2d',
        '--background-primary-translucent': 'rgba(45, 45, 45, 0.6)',
        '--background-secondary': '#3c3c3c',
        '--background-tertiary': '#4a4a4a',
        '--text-primary': '#f5f5f4',
        '--text-secondary': '#a8a29e',
        '--text-tertiary': '#eab308',
        '--primary-accent': '#eab308',
        '--primary-accent-hover': '#fde047',
        '--primary-accent-aurora': 'rgba(234, 179, 8, 0.15)',
        '--border-color': '#4a4a4a',
        '--border-radius': '0.25rem',
        '--header-gradient-from': '#eab308',
        '--header-gradient-to': '#fde047',
        '--bg-gradient-1': '#2d2d2d',
        '--bg-gradient-2': '#4a4a4a',
        '--bg-gradient-3': '#1c1c1c',
      },
      'high-contrast': highContrastStyles,
    },
  },
};


export const translations: Translations = {
  en: {
    'showcaseTitle': 'Showcase',
    'searchPlaceholder': 'Search products...',
    'surpriseMeTooltip': 'Surprise Me!',
    'commandPaletteTooltip': 'Command Palette (Ctrl+K)',
    'manageProductsTooltip': 'Manage Products',
    'wishlistTooltip': 'Wishlist ({count})',
    'cartTooltip': 'Cart ({count})',
    'settingsTooltip': 'Settings',
    'loadMore': 'Load More',
    'noProductsFound': 'No Products Found',
    'noProductsFoundDesc': 'Try adjusting your search or filter criteria.',
    'recentlyViewed': 'Recently Viewed',
    'footerSlogan': 'The ultimate product viewing experience.',
    'quickLinks': 'Quick Links',
    'aboutUs': 'About Us',
    'contact': 'Contact',
    'faq': 'FAQ',
    'followUs': 'Follow Us',
    'followUsDesc': 'Join our community on social media.',
    'copyright': '© {year} Showcase. All rights reserved.',
  },
  vi: {
    'showcaseTitle': 'Trưng bày',
    'searchPlaceholder': 'Tìm kiếm sản phẩm...',
    'surpriseMeTooltip': 'Gây bất ngờ cho tôi!',
    'commandPaletteTooltip': 'Bảng lệnh (Ctrl+K)',
    'manageProductsTooltip': 'Quản lý Sản phẩm',
    'wishlistTooltip': 'Danh sách Yêu thích ({count})',
    'cartTooltip': 'Giỏ hàng ({count})',
    'settingsTooltip': 'Cài đặt',
    'loadMore': 'Tải thêm',
    'noProductsFound': 'Không tìm thấy sản phẩm',
    'noProductsFoundDesc': 'Hãy thử điều chỉnh tiêu chí tìm kiếm hoặc bộ lọc của bạn.',
    'recentlyViewed': 'Đã xem gần đây',
    'footerSlogan': 'Trải nghiệm xem sản phẩm đỉnh cao.',
    'quickLinks': 'Liên kết nhanh',
    'aboutUs': 'Về chúng tôi',
    'contact': 'Liên hệ',
    'faq': 'Câu hỏi thường gặp',
    'followUs': 'Theo dõi chúng tôi',
    'followUsDesc': 'Tham gia cộng đồng của chúng tôi trên mạng xã hội.',
    'copyright': '© {year} Showcase. Mọi quyền được bảo lưu.',
  }
};

export const initialNotifications: Notification[] = [
    {
        id: 'welcome-1',
        type: 'general',
        title: 'Welcome to the Showcase!',
        message: 'Explore our new features like AI Stylist and Voice Navigation.',
        read: false,
        timestamp: Date.now() - 1000 * 60 * 5, // 5 minutes ago
    }
];
