import { Theme, AppTheme } from '../types';
import { electronicsProducts, youthfulProducts, fashionProducts, bookProducts } from './products';

const sharedLightStyles = {
    '--shimmer-color': 'rgba(0, 0, 0, 0.08)',
    '--badge-text-color': '#111827',
};

const sharedDarkStyles = {
    '--shimmer-color': 'rgba(255, 255, 255, 0.08)',
    '--badge-text-color': '#FFFFFF',
};

const highContrastStyles = {
    ...sharedDarkStyles,
    '--font-family': "'Poppins', sans-serif",
    '--background-primary': '#000000',
    '--background-primary-translucent': 'rgba(0, 0, 0, 0.8)',
    '--background-secondary': '#1a1a1a',
    '--background-tertiary': '#333333',
    '--text-primary': '#ffffff',
    '--text-secondary': '#e6e6e6',
    '--text-tertiary': '#cccccc',
    '--primary-accent': '#ffff00',
    '--primary-accent-hover': '#ffdd00',
    '--primary-accent-aurora': 'rgba(255, 255, 0, 0.2)',
    '--border-color': '#666666',
    '--border-radius': '0.25rem',
    '--header-gradient-from': '#ffff00',
    '--header-gradient-to': '#00ffff',
    '--bg-gradient-1': '#000000',
    '--bg-gradient-2': '#0a0a0a',
    '--bg-gradient-3': '#000000',
    '--badge-text-color': '#000000',
};

export const themes: Record<Theme, AppTheme> = {
  [Theme.Electronics]: {
    products: electronicsProducts,
    styles: {
      light: {
        ...sharedLightStyles,
        '--font-family': "'Poppins', sans-serif",
        '--background-primary': '#f9fafb',
        '--background-primary-translucent': 'rgba(249, 250, 251, 0.6)',
        '--background-secondary': '#ffffff',
        '--background-tertiary': '#f3f4f6',
        '--text-primary': '#111827',
        '--text-secondary': '#374151',
        '--text-tertiary': '#6b7280',
        '--primary-accent': '#0ea5e9',
        '--primary-accent-hover': '#38bdf8',
        '--primary-accent-aurora': 'rgba(14, 165, 233, 0.15)',
        '--border-color': '#e5e7eb',
        '--border-radius': '0.5rem',
        '--header-gradient-from': '#a78bfa',
        '--header-gradient-to': '#38bdf8',
        '--bg-gradient-1': '#f0f9ff',
        '--bg-gradient-2': '#e0f2fe',
        '--bg-gradient-3': '#f0f9ff',
      },
      dark: {
        ...sharedDarkStyles,
        '--font-family': "'Poppins', sans-serif",
        '--background-primary': '#111827',
        '--background-primary-translucent': 'rgba(17, 24, 39, 0.6)',
        '--background-secondary': '#1f2937',
        '--background-tertiary': '#374151',
        '--text-primary': '#f9fafb',
        '--text-secondary': '#d1d5db',
        '--text-tertiary': '#9ca3af',
        '--primary-accent': '#22d3ee',
        '--primary-accent-hover': '#67e8f9',
        '--primary-accent-aurora': 'rgba(34, 211, 238, 0.15)',
        '--border-color': '#374151',
        '--border-radius': '0.5rem',
        '--header-gradient-from': '#a78bfa',
        '--header-gradient-to': '#67e8f9',
        '--bg-gradient-1': '#0f172a',
        '--bg-gradient-2': '#1e293b',
        '--bg-gradient-3': '#132a4a',
      },
      'high-contrast': highContrastStyles,
    },
  },
  [Theme.Youthful]: {
    products: youthfulProducts,
    styles: {
        light: {
            ...sharedLightStyles,
            '--font-family': "'Poppins', sans-serif",
            '--background-primary': '#ffffff',
            '--background-primary-translucent': 'rgba(255, 255, 255, 0.6)',
            '--background-secondary': '#f9f9f9',
            '--background-tertiary': '#eef2f7',
            '--text-primary': '#1a1a2e',
            '--text-secondary': '#555770',
            '--text-tertiary': '#898a9a',
            '--primary-accent': '#e94560',
            '--primary-accent-hover': '#f36d84',
            '--primary-accent-aurora': 'rgba(233, 69, 96, 0.2)',
            '--border-color': '#eef2f7',
            '--border-radius': '1rem',
            '--header-gradient-from': '#f9a8d4',
            '--header-gradient-to': '#e94560',
            '--bg-gradient-1': '#fff1f2',
            '--bg-gradient-2': '#ffe4e6',
            '--bg-gradient-3': '#fff1f2',
        },
        dark: {
            ...sharedDarkStyles,
            '--font-family': "'Poppins', sans-serif",
            '--background-primary': '#1a1a2e',
            '--background-primary-translucent': 'rgba(26, 26, 46, 0.6)',
            '--background-secondary': '#16213e',
            '--background-tertiary': '#0f3460',
            '--text-primary': '#ffffff',
            '--text-secondary': '#a7a9be',
            '--text-tertiary': '#e94560',
            '--primary-accent': '#e94560',
            '--primary-accent-hover': '#f9a8d4',
            '--primary-accent-aurora': 'rgba(233, 69, 96, 0.2)',
            '--border-color': '#0f3460',
            '--border-radius': '1rem',
            '--header-gradient-from': '#f9a8d4',
            '--header-gradient-to': '#e94560',
            '--bg-gradient-1': '#1a1a2e',
            '--bg-gradient-2': '#16213e',
            '--bg-gradient-3': '#2e1a2a',
        },
        'high-contrast': highContrastStyles,
    },
  },
  [Theme.Fashion]: {
    products: fashionProducts,
    styles: {
      light: {
        ...sharedLightStyles,
        '--font-family': "'Playfair Display', serif",
        '--background-primary': '#f5f5f4',
        '--background-primary-translucent': 'rgba(245, 245, 244, 0.6)',
        '--background-secondary': '#ffffff',
        '--background-tertiary': '#e7e5e4',
        '--text-primary': '#2d2d2d',
        '--text-secondary': '#57534e',
        '--text-tertiary': '#78716c',
        '--primary-accent': '#ca8a04',
        '--primary-accent-hover': '#eab308',
        '--primary-accent-aurora': 'rgba(202, 138, 4, 0.15)',
        '--border-color': '#d6d3d1',
        '--border-radius': '0.25rem',
        '--header-gradient-from': '#fde047',
        '--header-gradient-to': '#ca8a04',
        '--bg-gradient-1': '#fefce8',
        '--bg-gradient-2': '#fef9c3',
        '--bg-gradient-3': '#fefce8',
      },
      dark: {
        ...sharedDarkStyles,
        '--font-family': "'Playfair Display', serif",
        '--background-primary': '#2d2d2d',
        '--background-primary-translucent': 'rgba(45, 45, 45, 0.6)',
        '--background-secondary': '#3c3c3c',
        '--background-tertiary': '#4a4a4a',
        '--text-primary': '#f5f5f4',
        '--text-secondary': '#a8a29e',
        '--text-tertiary': '#eab308',
        '--primary-accent': '#eab308',
        '--primary-accent-hover': '#fde047',
        '--primary-accent-aurora': 'rgba(234, 179, 8, 0.15)',
        '--border-color': '#4a4a4a',
        '--border-radius': '0.25rem',
        '--header-gradient-from': '#eab308',
        '--header-gradient-to': '#fde047',
        '--bg-gradient-1': '#2d2d2d',
        '--bg-gradient-2': '#4a4a4a',
        '--bg-gradient-3': '#1c1c1c',
      },
      'high-contrast': highContrastStyles,
    },
  },
  [Theme.Book]: {
    products: bookProducts,
    styles: {
      light: {
        ...sharedLightStyles,
        '--font-family': "'Playfair Display', serif",
        '--background-primary': '#fbfaf5',
        '--background-primary-translucent': 'rgba(251, 250, 245, 0.6)',
        '--background-secondary': '#ffffff',
        '--background-tertiary': '#f1ede9',
        '--text-primary': '#4a3f35',
        '--text-secondary': '#6e6055',
        '--text-tertiary': '#9d8f85',
        '--primary-accent': '#8B4513',
        '--primary-accent-hover': '#a0522d',
        '--primary-accent-aurora': 'rgba(139, 69, 19, 0.15)',
        '--border-color': '#e0d8d1',
        '--border-radius': '0.375rem',
        '--header-gradient-from': '#c0a080',
        '--header-gradient-to': '#8B4513',
        '--bg-gradient-1': '#fbfaf5',
        '--bg-gradient-2': '#f1ede9',
        '--bg-gradient-3': '#fbfaf5',
      },
      dark: {
        ...sharedDarkStyles,
        '--font-family': "'Playfair Display', serif",
        '--background-primary': '#1c1a19',
        '--background-primary-translucent': 'rgba(28, 26, 25, 0.6)',
        '--background-secondary': '#2a2725',
        '--background-tertiary': '#383432',
        '--text-primary': '#e8e0d4',
        '--text-secondary': '#b8ada0',
        '--text-tertiary': '#8a7f75',
        '--primary-accent': '#d2b48c',
        '--primary-accent-hover': '#e0cda9',
        '--primary-accent-aurora': 'rgba(210, 180, 140, 0.15)',
        '--border-color': '#383432',
        '--border-radius': '0.375rem',
        '--header-gradient-from': '#e0cda9',
        '--header-gradient-to': '#d2b48c',
        '--bg-gradient-1': '#1c1a19',
        '--bg-gradient-2': '#2a2725',
        '--bg-gradient-3': '#121110',
      },
      'high-contrast': highContrastStyles,
    },
  },
};
